"""add_rank_to_levels

Revision ID: 914ef2af6dff
Revises: a3d6538e763c
Create Date: 2026-02-02 18:38:02.533910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914ef2af6dff'
down_revision = 'a3d6538e763c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_level_rank', ['rank'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_constraint('uq_level_rank', type_='unique')
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
