"""Add points to Level and is_first_victor to Claim

Revision ID: a3d6538e763c
Revises: b7eb91bf3265
Create Date: 2026-02-02 18:07:22.900053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d6538e763c'
down_revision = 'b7eb91bf3265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_victor', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('is_first_victor')

    # ### end Alembic commands ###
